/*
 * Constants.swift
 * Project: Space Invaders
 * Students:
 *          Irvinder Kaur           300929258
 *          Kamalpreet Singh        300976062
 *          Mehmet Fatih Inan       300966544
 *          Robert Argume           300949529
 *
 * Date: Mar 22, 2018
 * Description: Constants that will be used along the project
 * Version: 0.1
 *     - Add constants to setup enemies 
 */

import Foundation
import SpriteKit
import GameplayKit


// Constants used to initialize enemies
let numberOfRows:Int = 5
let enemiesPerRow:Int = 6
let firstRowPositionX: Double = 60.0
let firstRowPositionY: Double = 404.0
let separationX: Double = 55.0
let velocityX: CGFloat = 0.9
let separationY: Double = 45.0
let avatars = ["alien3", "alien2", "alien1"]
let scales = [ 0.06, 0.06, 0.015]

// Constants used for creating enemy bugs and shooting enemy bullets
let BossNodeName = "boss"
let BugNodeName = "bug"
let BugBulletName = "BugBullet"
let BulletSize = CGSize(width:4, height: 8)

// Constants for bullet generated by our hero
let DefenderBulletAction = "fireDefenderBullet"
let DefenderName = "weapon"

// Constants used scoring
let PointsForBug = 50
let PointsForBoss = 200

